import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Link from "next/link";
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home({blog}) {
  const router = useRouter()
  console.log(blog)
  let show=()=>{
    router.push('/mine')
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div style={{border : "1px solid white",lineHeight:"25px", textAlign:"center"}}>
      <h1 key={blog.id}><u>github detail</u></h1>
      <br/>
      <img src="https://avatars.githubusercontent.com/u/107989068?v=4" alt="" width={100} height={100}/>
      <p>githubIntro : {blog.name}</p>
      <br/>
      <p>Resume : {blog.blog}</p>
      <p>TechStack : {blog.bio}</p>
      <p>experience : {blog.company}</p>
      <hr/>
      <br/>
      <Link href="./mine">
      <button onClick={show}>Show All Projects</button>
      </Link>
      <hr/>
      </div>
      </main>
    </>
  )
}
export async function getStaticProps(){
  let user="mira713"
  let res= await fetch(`https://api.github.com/users/${user}`);
  let data = await res.json();
  //console.log(data);
  return {
    props : {
       blog : data
    }
  }
}

